name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Ensure you have a requirements.txt with sphinx and sphinx_rtd_theme

      - name: Build Sphinx documentation
        run: sphinx-build -b html docs/source docs/build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.0.0
        with:
          branch: gh-pages  # Push to gh-pages branch
          folder: docs/build  # Folder with the built docs
